# Generated by Django 4.0.6 on 2022-08-30 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='racepilot',
            table='race_pilot',
        ),
    ]
