# Generated by Django 4.0.6 on 2022-08-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='championship',
            table='championship',
        ),
        migrations.AlterModelTable(
            name='descent',
            table='descent',
        ),
        migrations.AlterModelTable(
            name='race',
            table='race',
        ),
        migrations.AlterModelTable(
            name='track',
            table='track',
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venue',
        ),
    ]
