# Generated by Django 4.0.6 on 2022-08-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_championship_table_alter_descent_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descent',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
