# Generated by Django 4.0.6 on 2022-08-31 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_racepilot_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='descent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='descent',
            name='race_pilot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='descents', to='api.racepilot'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='descent',
            unique_together={('race_pilot', 'track')},
        ),
        migrations.RemoveField(
            model_name='descent',
            name='pilot',
        ),
        migrations.RemoveField(
            model_name='descent',
            name='race',
        ),
    ]
