# Generated by Django 4.0.6 on 2022-09-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_descent_unique_together_descent_race_pilot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descent',
            name='month',
            field=models.IntegerField(choices=[(1, 'Dns'), (2, 'Running'), (3, 'Paused'), (4, 'Dnf')], default=1),
        ),
    ]
