# Generated by Django 4.0.6 on 2022-08-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_descent_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='pilots',
            field=models.ManyToManyField(to='api.pilot'),
        ),
    ]
