# Generated by Django 4.0.6 on 2022-09-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_descent_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descent',
            old_name='month',
            new_name='status',
        ),
    ]
