# Generated by Django 4.0.6 on 2022-09-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_month_descent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descent',
            name='status',
            field=models.IntegerField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('finished', 'Finished'), ('dns', 'Dns'), ('dnf', 'Dnf')], default='dns'),
        ),
    ]
