# Generated by Django 4.0.6 on 2022-08-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_descent_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descent',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='descent',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
