# Generated by Django 4.0.6 on 2022-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_descent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('finished', 'Finished'), ('dns', 'Dns'), ('dnf', 'Dnf')], default='pending', max_length=20),
        ),
    ]
