# Generated by Django 4.0.6 on 2023-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_descent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descent',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descent',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='racepilot',
            unique_together={('race', 'number')},
        ),
    ]
