# Generated by Django 4.0.6 on 2022-08-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_descent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descent',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descents', to='api.pilot'),
        ),
    ]
