# Generated by Django 4.0.6

from django.db import migrations, models
import django.db.models.deletion


def create_standard_track_variations(apps, schema_editor):
    """Create a standard (no variation) TrackVariation for each existing Track."""
    Track = apps.get_model('api', 'Track')
    TrackVariation = apps.get_model('api', 'TrackVariation')
    for track in Track.objects.all():
        TrackVariation.objects.get_or_create(track=track, description='')


def migrate_descent_track_to_track_variation(apps, schema_editor):
    """Set track_variation for each Descent from its track's standard variation."""
    Descent = apps.get_model('api', 'Descent')
    TrackVariation = apps.get_model('api', 'TrackVariation')
    for descent in Descent.objects.all():
        track_variation = TrackVariation.objects.get(track=descent.track, description='')
        descent.track_variation = track_variation
        descent.save()


def reverse_migrate_descent(apps, schema_editor):
    """Restore track from track_variation for rollback."""
    Descent = apps.get_model('api', 'Descent')
    for descent in Descent.objects.all():
        descent.track = descent.track_variation.track
        descent.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_descent_end_alter_descent_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Description of the variation (e.g. "Bypass area under reparation"). Leave blank for standard route.', max_length=255)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='api.track')),
            ],
            options={
                'db_table': 'track_variation',
            },
        ),
        migrations.RunPython(create_standard_track_variations, migrations.RunPython.noop),
        migrations.AddField(
            model_name='descent',
            name='track_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descents', to='api.trackvariation'),
        ),
        migrations.RunPython(migrate_descent_track_to_track_variation, reverse_migrate_descent),
        migrations.RemoveField(
            model_name='descent',
            name='track',
        ),
        migrations.AlterField(
            model_name='descent',
            name='track_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descents', to='api.trackvariation'),
        ),
        migrations.AlterUniqueTogether(
            name='descent',
            unique_together={('race_pilot', 'track_variation')},
        ),
    ]
