# Generated by Django 4.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trackvariation_and_descent_track_variation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trackvariation',
            constraint=models.UniqueConstraint(
                condition=models.Q(description=''),
                fields=('track',),
                name='unique_standard_variation_per_track',
            ),
        ),
    ]
